### PR TITLE
Add ability to pick representative from a list

### PR DESCRIPTION
**Pull request by owczaro**
Basically it's a copy paste from natrium wallet with few improvements:

- current representative alias has primary color
- sort order: firstly by `uptimePercentSemiAnnual` and then by `weight` (it will help with decentralisation process)

### CODE REVIEW

**Comment by owczaro** [comment]
I can add two popups on the homepage:
- every time, when there is no representative (about 4.7% network voting weight), we can set it automatically and notify a user about it
- disposable or once-per-month popup encouraging user to change representative to one with lower voting weight - only for users using representatives with voting weight > 20%

It will be great to add a notify bar when rep is offline.

**Comment by bbedward** [comment]
Who runs the yellow spyglass service? I haven't seen it before.

**Comment by owczaro** [comment]
@bbedward, [some monkey from r/banano](https://www.reddit.com/r/banano/comments/ocgj5u/just_wanted_to_share_my_banano_booster_project/). But if you have more reliable source of necessary data I can use yours.

**Comment by yekta** [comment]
Hey, can you re-submit the PR and target the `replist` branch?

**Comment by owczaro** [comment]
Hi @yekta, I've changed the base branch in current PR

**Comment by yekta** [comment]
Thanks. I'll need to review but if everything looks good we'll merge with the main branch.

**Pull request merged**
